site_name: Sean
site_description: My personal digital garden
site_author: Sean
site_url: https://Joon-Park92.github.io
nav:
  - "0":
      - Introduction:
          - index: epics/para-area/TSK-1300-blog/docs/index.md
  - "1":
      - Think: []
  - "2":
      - Programming: []
  - "3":
      - Mathematics:
          - 2023-06-01-distance_vs_metric_vs_norm: epics/para-area/TSK-1300-blog/docs/2023-06-01-distance_vs_metric_vs_norm.md
          - 2023-06-11-modern-mathematics: epics/para-area/TSK-1300-blog/docs/2023-06-11-modern-mathematics.md
          - 2023-06-01-completeness_soundness_consistency: epics/para-area/TSK-1300-blog/docs/2023-06-01-completeness_soundness_consistency.md
          - 2023-07-10-analysis-basic: epics/para-area/TSK-1300-blog/docs/2023-07-10-analysis-basic.md
          - 2023-06-11-formal_system: epics/para-area/TSK-1300-blog/docs/2023-06-11-formal_system.md
          - 2023-07-10-tensor: epics/para-area/TSK-1300-blog/docs/2023-07-10-tensor.md
  - "4":
      - Papers:
          - two_step_ml_enable_optimized_nanoparticle_synthesis: epics/para-area/TSK-1300-blog/docs/two_step_ml_enable_optimized_nanoparticle_synthesis.md
plugins:
  - search
  - exclude-search:
      exclude:
        - newsletter/*
  - autolinks
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
  - section-index
  - mkdocs-newsletter
markdown_extensions:
  - abbr
  - admonition
  - meta
  - def_list
  - toc:
      permalink: ⚑
      baselevel: 2
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: "!!python/name:pymdownx.emoji.to_svg"
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.extra
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - mdx_math
theme:
  name: material
  custom_dir: theme
  logo: img/logo.png
  features:
    - navigation.footer
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - search.suggest
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
  - stylesheets/links.css
extra_javascript:
  - path: assets/js/mathjaxhelper.js
    defer: true
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/lyz-code
    - icon: fontawesome/solid/rss
      link: https://lyz-code.github.io/blue-book/newsletter/0_newsletter_index
repo_name: Joon-Park92/Joon-Park92.github.io
repo_url: https://github.com/Joon-Park92/Joon-Park92.github.io
