---
site_name: Sean
site_description: My personal digital garden
site_author: Sean
site_url: https://Joon-Park92.github.io
nav:
  - Introduction:
    - index.md
  - Think:
    - Problem : what_is_problem.md
    - Innovation : what_is_innovation.md
  - Project:
    - project.md
  - Programming:
    - DB:  
      - 2023-06-06-db-transaction.md
  - Mathematics:
    - mathematics/2023-06-01-distance_vs_metric_vs_norm.md
    - mathematics/2023-06-11-modern-mathematics.md
    - mathematics/2023-06-01-completeness_soundness_consistency.md
    - mathematics/2023-07-10-analysis-basic.md
    - mathematics/2023-06-11-formal_system.md
    - mathematics/2023-07-10-tensor.md

plugins:
  - search
  - exclude-search:
      exclude: [newsletter/*]
  - autolinks
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
  - section-index
  - mkdocs-newsletter

markdown_extensions:
  - abbr
  - admonition
  - meta
  - def_list
  - toc:
      permalink: ⚑
      baselevel: 2
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: '!!python/name:pymdownx.emoji.to_svg'
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - mdx_math
theme:
  name: material
  custom_dir: theme
  logo: img/logo.png
  features:
    - navigation.footer
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - search.suggest
    - search.highlight

  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css: [stylesheets/extra.css, stylesheets/links.css]
extra_javascript:
  - path: assets/js/mathjaxhelper.js
    defer: true
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/lyz-code
    - icon: fontawesome/solid/rss
      link: https://lyz-code.github.io/blue-book/newsletter/0_newsletter_index

repo_name: Joon-Park92/Joon-Park92.github.io
repo_url: https://github.com/Joon-Park92/Joon-Park92.github.io
